version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ~/.m2:/root/.m2   # Mount Maven local repository cache as a volume for caching dependencies
